import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/global.scss'
import Footer from '@/components/global/footer'

export const metadata: Metadata = {
  title: "Landing Page - Men's Health Quiz",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
